### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Luckino** [danrovito/pokephp#10]
Using php 7.1
composer 1.3.0  

Problem 1
    - The requested package danrovito/pokephp No version set (parsed as 1.0.0) is satisfiable by danrovito/pokephp[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

**Comment by danrovito** [comment]
I'll try to do an install this evening and see whats going on.

**Comment by danrovito** [comment]
if you do `composer require danrovito/pokephp` it should bring down the 1.2 version and I believe that should be marked as stable.
