### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by command76** [danrovito/pokephp#12]
I'm new to Php.  I used composer to import the necessary files for the Pokemon API PhpWrapper and I get this error.  Fatal error: Class 'PokePHP\PokeApi' not found in /applications/index.php on line 4.  I tried multiple fixes and can't find out what is wrong.  Can you help me with this?

**Comment by danrovito** [comment]
I'll check the package and see if it has a bug. Are you making sure to include the class in your file? Try doing '\PokePHP\PokeApi ' if you aren't using a use statement at the top of your file.
